# Generated by Django 6.0.2 on 2026-04-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Dipesan'), ('CHECKED_IN', 'Check-In'), ('COMPLETED', 'Selesai')], default='BOOKED', max_length=20),
        ),
    ]
