# Generated by Django 6.0.2 on 2026-04-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image_url',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
